### ISSUE TITLE
Mất texture skin kiếm

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#11]
Skin kiếm sẽ quay lại kiếm bình thường nếu right click vào NPC, nhấn chuột vào trong kho đồ
![2021-12-01_11 16 33](https://user-images.githubusercontent.com/63439671/144171256-1ae55a6d-dd18-4b49-a2df-34b8c9ffb0ce.png)

**Comment by amadeusmz** [comment]
chém người khác là có lại skin
