### ISSUE TITLE
Không thể nhìn thấy người chơi khác khi spectate (Bedwars)

### ISSUE THREAD

**Issue by acayrin** [MineVN/Minigames-issues#12]
Không thể nhìn thấy người chơi khác khi làm khán giả trong Bedwars (1.12.2 + 1.16.5)
- Chỉ có thể nhìn thấy được khi player hồi sinh
- Gamemode 3 cũng không thấy 

Reproduce
- Khi vào trận
- Khi tham gia mid game

**Comment by WaIaF** [comment]
cool

**Comment by amadeusmz** [comment]
em bị ở phiên bản mc nào?

**Comment by acayrin** [comment]
e thử 1.12 với 1.16 luôn rồi, vẫn bị
có thêm vài người khác cũng gặp trường hợp tương tự

**Comment by amadeusmz** [comment]
vừa test thấy bị trên 1.17.1 luôn, update bedwars gần đây bị sida rồi

**Comment by amadeusmz** [comment]
fixed
