### ISSUE TITLE
Crash game khi thoát ra sảnh 

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#13]
- Xuất hiện từ khi thêm skin kiếm
- Ảnh hưởng đến tận 1.16
- Ảnh hưởng ở Optifine, custom client 
- Crash report 1: https://pastebin.com/1LuBr6wU
- Crash report 2: https://pastebin.com/VQPKk4RU

Reproduce:
- Spec một game nào đó (Bedwars atm)
- Dùng lệnh /leave hoặc nhấn vào bed

**Comment by amadeusmz** [comment]
Lỗi này do ViaBackwards, tạm thời revert về bản 4.0.1 là hết bị
Trong thời gian này server sẽ không thể support 1.18
https://github.com/ViaVersion/ViaBackwards/issues/408

**Comment by minhh2792** [comment]
Okay

**Comment by amadeusmz** [comment]
up viaver lên 4.1.1 là hết bị, server hiện đã support 1.18
