### ISSUE TITLE
Lệnh /call để gọi pô líc

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#16]
Member trong phòng khi phát hiện hack sẽ dùng lệnh /call <người chơi nghi vấn> (optional) để gọi pô líc đang online

**Comment by WaIaF** [comment]
ko

**Comment by minhh2792** [comment]
![image](https://user-images.githubusercontent.com/63439671/146324418-9d7dc629-f5d9-4320-ad99-2c6294d125fd.png)
