### ISSUE TITLE
Đôi lúc vẫn thấy được menu tab cũ/menu tab của essentialsx

### ISSUE THREAD

**Issue by cheesethesylveon** [MineVN/Minigames-issues#18]
Không biết cái này có tính là bug không, nhưng đôi lúc lag nhẹ thì thấy.

**Comment by minhh2792** [comment]
Server ko dùng essentialsX
Nếu ở sảnh thì do TAB
Nếu trong phòng thì không biết, ko đáng kể lắm nên won't fix
