### ISSUE TITLE
Slave không chạy khi start game

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#4]
https://www.facebook.com/groups/minevn.net/posts/1109139256156887/

Slave không chạy khi start game, chỉ có "Đang bắt đầu trận...", không có chữ đỏ "Có lỗi xảy ra, hãy báo cho BQT". Người chơi cũng sẽ bị kẹt trong phòng, không thể giải thoát bằng cách thoát/kill/ban. Log không có gì bất thường

Member trong video bị kẹt từ trưa đến chiều.

**Comment by minhh2792** [comment]
lol ko add labels dc

**Comment by amadeusmz** [comment]
cho phép out ở trạng thái đang bắt đầu sẽ ko còn bị kẹt.
