### ISSUE TITLE
Chat tổng ở solo (Bedwars)

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#5]
Tự động chuyển tin nhắn sang Global ở chế độ solo thay vì phải thêm !

**Comment by amadeusmz** [comment]
tạo issue bên bw1058 đi

**Comment by minhh2792** [comment]
thực chất lỗi này là do mình
vì group solo/duo bên mình teamsize là 2 nên nó ko tự động 

gonna find new solution

**Comment by minhh2792** [comment]
Fixed
