### ISSUE TITLE
Ảnh treo trong phòng bị rơi (?)

### ISSUE THREAD

**Issue by minhh2792** [MineVN/Minigames-issues#7]
![image](https://user-images.githubusercontent.com/63439671/142355509-4ad06574-3dcf-4e98-b5d4-89354fc6fcd7.png)

**Comment by cheesethesylveon** [comment]
đào lại tí nhưng em thấy ảnh treo trong phòng có lúc bị rơi, maybe giảm cái despawn rate xuống còn 5-10s?
